Spring XD Analytics ML - PMML
=============================

== Introduction
This  XD processor provides support for real-time evaluation of various machine learning scoring algorithms.
It is based on the https://github.com/jpmml/jpmml-evaluator[JPMML-Evaluator] library that provides support for a wide range of https://github.com/jpmml/jpmml-evaluator#features[model types] and is interoperable with models exported from https://www.r-project.org/[R], https://rattle.togaware.com/[Rattle], https://www.knime.org/[KNIME], and https://rapid-i.com/content/view/181/190/[RapidMiner].  The JPMML-Evaluator is https://www.gnu.org/licenses/agpl-3.0.html[AGPL] licenced.

== Build and Install
To build, clone this repository. Then cd to `analytics-ml-pmml` and type

```
./gradlew clean test bootRepackage
```

To install this processor into Spring XD you will need to either copy the resulting jar to the registry at `$XD_HOME/modules/processor/analytic-pmml.jar` or use the `module upload` command from the shell.


== Module usage
For an example of the module usage, see 

This module supports the following options at the time of writing:
```
xd:>module info --name processor:analytic-pmml
Information about processor module 'analytic-pmml':

  Option Name         Description                                            Default  Type
  ------------------  -----------------------------------------------------  -------  --------
  inputFieldMapping   mapping of input tuple fields to model input fields    <none>   String
  location            the location of the PMML xml file                      <none>   String
  modelName           the name of the model to use, from the PMML document   <none>   String
  outputFieldMapping  mapping of model output fields to output fields        <none>   String
  outputType          how this module should emit messages it produces       <none>   MimeType
  inputType           how this module should interpret messages it consumes  <none>   MimeType
```

== Usage example
For an usage example please have a look at the https://github.com/spring-projects/spring-xd-samples/tree/master/analytics-pmml[analytics-pmml] sample project in the https://github.com/spring-projects/spring-xd-samples[spring-xd-samples] github repository.
